import fs from 'fs-extra';
import path from 'path';
import { logger, confirm, ICONS, STYLES, createSpinner, formatSize, createBox, THEME } from './ui.js';
import chalk from 'chalk';

// ============================================================
// PLUGIN BOILERPLATE TEMPLATES
// ============================================================
function createManyplugJson(name, category, service = false) {
	return {
		name,
		version: '1.0.0',
		description: `${name} plugin for ManyBot`,
		category,
		service,
		author: '',
		license: 'MIT',
		main: 'index.js',
		dependencies: {},
		externalDependencies: {}
	};
}

function createIndexJs(name) {
	return `// ${name} plugin for ManyBot
// Generated by manyplug

import { CMD_PREFIX } from "../../config.js"

export default async function ({ msg, api }) {
  if (!msg.is(CMD_PREFIX + "hi")) return;

  await msg.reply("Hello!");
}
`;
}

function createLocalePt(name) {
	return {
		plugin: {
			name: name,
			description: `Plugin ${name} para ManyBot`
		},
		commands: {
			// Add your command translations here
		}
	};
}

function createLocaleEn(name) {
	return {
		plugin: {
			name: name,
			description: `${name} plugin for ManyBot`
		},
		commands: {
			// Add your command translations here
		}
	};
}

function createGitignore() {
	return `# Dependencies
node_modules/
package-lock.json

# Logs
*.log
npm-debug.log*

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Test coverage
coverage/
`;
}

function createReadme(name) {
	return `# ${name}

Plugin for ManyBot.

## Installation

\`\`\`bash
manyplug install ${name}
\`\`\`

## Usage

Describe how to use your plugin here.

## Commands

List your plugin commands here.

## License

MIT
`;
}

// ============================================================
// UTILS
// ============================================================
async function delay(ms) {
	return new Promise(resolve => setTimeout(resolve, ms));
}

async function getDirectorySize(dirPath) {
	let totalSize = 0;

	async function calc(currentPath) {
		const stats = await fs.stat(currentPath);

		if (stats.isFile()) {
			totalSize += stats.size;
		} else if (stats.isDirectory()) {
			const items = await fs.readdir(currentPath);

			for (const item of items) {
				await calc(path.join(currentPath, item));
			}
		}
	}

	await calc(dirPath);
	return totalSize;
}

// ============================================================
// VALID CATEGORIES
// ============================================================
const VALID_CATEGORIES = ['games', 'media', 'utility', 'service', 'admin', 'fun'];

// ============================================================
// INIT COMMAND
// ============================================================
export async function initCommand(name, options = {}) {
	const startTime = Date.now();

	// Validate name
	if (!name || !/^[a-z0-9-]+$/.test(name)) {
		logger.error('Invalid plugin name. Use only lowercase letters, numbers, and hyphens.');
		process.exit(1);
	}

	// Check if plugin already exists
	const pluginDir = path.resolve(name);
	if (await fs.pathExists(pluginDir)) {
		logger.warn(`Directory "${name}" already exists`);
		const overwrite = await confirm('Overwrite existing files?', false);
		if (!overwrite) {
			logger.info('Aborted');
			process.exit(0);
		}
	}

	// Determine category
	let category = options.category;
	if (!category || !VALID_CATEGORIES.includes(category)) {
		category = 'utility'; // default
		logger.warn(`Unknown category. Using "${category}"`);
	}

	const service = options.service || false;

	logger.newline();
	logger.header('Initialize Plugin');

	// Show configuration
	const configLines = [
		`${ICONS.package} ${chalk.bold.white(name)}`,
		`${chalk.gray('Category:')} ${chalk.cyan(category)}`,
		`${chalk.gray('Service:')} ${service ? chalk.cyan('yes') : chalk.gray('no')}`,
	];
	console.log(createBox(configLines.join('\n'), { width: 50 }));

	const spinner = createSpinner('Creating plugin structure...');
	spinner.start();

	try {
    const file = (...p) => path.join(pluginDir, ...p);

		// Create directory structure
		await fs.ensureDir(path.join(pluginDir, 'locale'));
		spinner.setText('Creating configuration...');
		await delay(100);

		// Write files
		const manyplugJson = createManyplugJson(name, category, service);
		await fs.writeJson(file('manyplug.json'), manyplugJson, { spaces: 2 });

		spinner.setText('Creating entry point...');
		await delay(100);
		await fs.writeFile(file('index.js'), createIndexJs(name));

		spinner.setText('Creating locale files...');
		await delay(100);
    await Promise.all([
		  await fs.writeJson(file('locale', 'pt.json'), createLocalePt(name), { spaces: 2 }),
		  await fs.writeJson(file('locale', 'en.json'), createLocaleEn(name), { spaces: 2 })
    ]);

		spinner.setText('Creating additional files...');
		await delay(100);
		await fs.writeFile(file('.gitignore'), createGitignore());
		await fs.writeFile(file('README.md'), createReadme(name));

		const size = await getDirectorySize(pluginDir);

		spinner.succeed('Plugin created successfully');

		// Summary
		const duration = Date.now() - startTime;
		logger.newline();
		logger.header('Plugin Summary');
		logger.separator();
		console.log(`  ${ICONS.package} ${chalk.bold.white(name)}`);
		console.log(`  ${STYLES.item('Version', manyplugJson.version)}`);
		console.log(`  ${STYLES.item('Category', category)}`);
		console.log(`  ${STYLES.item('Service', service ? 'yes' : 'no')}`);
		console.log(`  ${STYLES.item('Location', pluginDir)}`);
		console.log(`  ${STYLES.item('Size', formatSize(size))}`);
		logger.separator();

		logger.newline();
		logger.info('Next steps:');
		console.log(`  ${ICONS.arrow} ${chalk.cyan('cd ' + name)}`);
		console.log(`  ${ICONS.arrow} ${chalk.cyan('manyplug validate .')} ${chalk.gray('(validate your plugin)')}`);
		console.log(`  ${ICONS.arrow} ${chalk.cyan('manyplug install --local .')} ${chalk.gray('(install locally)')}`);

		logger.newline();
		console.log(chalk.gray(`  Done in ${(duration / 1000).toFixed(2)}s`));

	} catch (err) {
		spinner.fail(`Failed to create plugin: ${err.message}`);
		process.exit(1);
	}
}
